# This workflow runs whenever a pull request is created. It simply does a `cdk synth` on the stack to see if it
# actually compiles into JSON. There is NO deployment happening.

name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  DEPLOY_ENV: CI
  AWS_REGION: eu-west-1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.3.0'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache npm modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm

      - name: Cache Pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install CDK
        run: |
          npm install -g aws-cdk

      - name: Install python virtualenv
        run: |
          pip install --upgrade pip
          python3 -m venv .venv
          source .venv/bin/activate

      - name: Install pip requirements for CDK
        run: |
          pip install -r requirements.txt

      - name: Synth CDK
        run: |
          cdk synth
